version: 2.1
jobs:
  build:
    docker:
      - image: oktomx/project-konami:0.0.1
    steps:
      - checkout
      - run: gcc -v
      - run: echo "Simple artifact" >> sample.txt
      - run: mkdir build && touch build/file.o
      - persist_to_workspace:
          root: .
          paths:
            - sample.txt
            - build/*
  test:
    docker:
      - image: oktomx/project-konami:0.0.1
    steps:
      - checkout 
      - attach_workspace:
        at: /tmp/workspace
      - >-
        run:
        cat /tmp/workspace/sample.txt
        && ls /tmp/workspace/build