version: 2.1
jobs:
  build:
    docker:
      - image: oktomx/project-konami:0.0.1
    steps:
      - checkout
      - run: gcc -v
      - run: echo "Simple artifact" >> sample.txt
      - run: mkdir build && touch build/file.o
      - persist_to_workspace:
          root: "."
          paths:
            - sample.txt
            - build/*
  test:
    docker:
      - image: oktomx/project-konami:0.0.1
    steps:
      - attach_workspace:
        at: "."
      - run: |
          cat sample.txt \
          && ls build
workflows:
  ci-workflow:
    jobs:
      - build
      - test:
        requires:
          - build