version: 2.1
jobs:
  build:
    docker:
      - image: oktomx/project-konami:0.0.1
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world\n" && ls # run the `echo` command