version: 2.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: mkdir build && cd build && cmake .. && make -j4 && cd ..
      - persist_to_workspace:
          root: build
          paths:
            - project/ProjectKonami
            - utests/Test
  test:
    executor: default
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: "build"
      - run: utests/run_unittests.sh build/utests/Test
  deploy:
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: "build"
      - run: |
          mkdir /tmp/git_repo && mv -t /tmp/git_repo \
          build/project/ProjectKonami project/resources \
          herokuDockerfile heroku.yml db_conf.json \
          project/simplechat.xml project/*.css \
          && git config --global user.email $GIT_EMAIL \
          && git config --global user.name $GIT_USERNAME \
          && cd /tmp/git_repo && git init && git add . && git commit -am "Deploy"
      - heroku/deploy-via-git:
          branch: "master"
          force: true
workflows:
  version: 2
  ci-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - dev-wt-server
executors:
  default:
    docker:
    - image: oktomx/project-konami:1.2
  lightweight:
    docker:
    - image: cimg/base:stable
orbs:
  heroku: circleci/heroku@1.0.1