version: 2.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: gcc -v
      - run: echo "Simple artifact" >> sample.txt
      - run: mkdir build && touch build/file.o
      - persist_to_workspace:
          root: "."
          paths:
            - sample.txt
            - build/*
  test:
    executor: default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - run: |
          cat sample.txt \
          && ls build
  deploy:
    # branches:
    #   only:
    #     - dev
    executor: heroku/default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - heroku/install
      - heroku/deploy-via-git
workflows:
  ci-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
executors:
  default:
    docker:
    - image: oktomx/project-konami:0.0.1
orbs:
  heroku: circleci/heroku@1.0.1