version: 2.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: gcc -v
      - run: echo "Simple artifact" >> sample.txt
      - run: mkdir build && touch build/file.o
      - persist_to_workspace:
          root: "."
          paths:
            - sample.txt
            - build/*
  test:
    executor: default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - run: |
          cat sample.txt \
          && ls build
  deploy:
    # branches:
    #   only:
    #     - dev
    executor: heroku/default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - run: |
          git config --global user.email $GIT_EMAIL \
          && git config --global user.name $GIT_USERNAME \
          && git init && git add . && git commit -am "Add deployment files"
      - heroku/deploy-via-git:
          branch: "master"
workflows:
  ci-workflow:
    jobs:
      - deploy
      # - build
      # - test:
          # requires:
            # - build
      # - deploy:
          # requires:
            # - test
executors:
  default:
    docker:
    - image: oktomx/project-konami:0.0.1
orbs:
  heroku: circleci/heroku@1.0.1