version: 2.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: g++ main.cpp
      - run: mkdir build && mv a.out build/ProjectKonami
      - persist_to_workspace:
          root: "build"
          paths:
            - ProjectKonami
  test:
    executor: default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - run: ls .
      - run: ./ProjectKonami
  deploy:
    # branches:
    #   only:
    #     - dev
    executor: heroku/default
    resource_class: small
    steps:
      - attach_workspace:
          at: "."
      - run: |
          git config --global user.email $GIT_EMAIL \
          && git config --global user.name $GIT_USERNAME \
          && git init && git add . && git commit -am "Add deployment files"
      - heroku/deploy-via-git:
          branch: "master"
workflows:
  ci-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
executors:
  default:
    docker:
    - image: oktomx/project-konami:1.0
  lightweight:
    docker:
    - image: cimg/base:stable
orbs:
  heroku: circleci/heroku@1.0.1